spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskmanager_scheduler
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/taskmaster-app
