spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:http://config-server:8888

server:
  port: 8090

spring.boot.admin:
  context-path: /admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PASSWORD:eureka_secret}@service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
